---
- hosts: all
  become: true
  tasks:
    - name: Create a padar user
      tags: always
      user:
        name: padar
        groups: root

    - name: Add SSH Keys for padar
      tags: always
      authorized_key:
        user: padar
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtq98LSrHeNcXW+dSg1fraZOPljHB+ZGoNRubtSbZ/75QnLcX7xPsErZm1hNNC7RFJLucU71kTjG4x+PKT/zScmI892ONmjlfrVLzlpKZ5A8LpbAScOQBpyPSbax6cJc5PqOhlOf48eFB/l60bMG/IsjELUU8uIjNBvPbI+HIByzVPj3MBH1rrI+4wgTg1HZQA2/YrejVY21edqafRzyyYY/rrY+RWd/IJPF8Waq6RL8BimSsnQ/LvQJCafm0eiPlbdRBSopEmG5ay2tcIe/IRWtOm0fjDtA8jgvQS4tI/58WgHklFnR6OZaU3E2GT33NvfKR71gTi5Gx9v8yEqynZDe1eix6f1oqaz7RixaHGLgYccm85i+lyDISOOiZRuLLSTWE/MnB9S8icGXJrNnIBC7C94Zm/3FKN6j9NFFwdBaF89HCnRjx32j7XCHz69NxYymv5Sjmlr3fIaZ04Y6/d4cYNyczv8iPZdrhPEA+0WlCHJDJTM7W01rGJQtRF540= vagrant@main"

    - name: Add Sudoers file for padar
      tags: always
      copy:
        src: ../files/sudoer_padar
        dest: /etc/sudoers.d/padar
        owner: root
        group: root
        mode: 0440

    - name: Update and Upgrade Package Manager on Ubuntu
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update and Upgrade Package Manager on CentOS
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
    
    - name: Install Apache on Ubuntu and CentOS
      package:
        name:
          - "{{ apache_package }}"
        state: latest

    - name: Start Apache
      tags: apache
      service:
        name: "{{ apache_package }}"
        state: started
        enabled: yes

    - name: Copy custom html files
      copy:
        src: ../files/site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0664
